apiVersion: v1
data:
  mysqlPd: KUBEFLOW-NAME-storage-metadata-store # {"type":"string","x-kustomize":{"setBy":"kpt","partialSetters":[{"name":"name","value":"KUBEFLOW-NAME"}]}}
kind: ConfigMap
metadata:
  name: pipeline-mysql-install-config
