apiVersion: v1
data:
  appName: dev-4-7 # {"$kpt-set":"name-label"}
  hostname: dev-4-7.endpoints.gongyuan-dev.cloud.goog # {"$kpt-set":"hostname"}
  ipName: dev-4-7-ip # {"$kpt-set":"ip-name"}
  project: "gongyuan-dev" # {"$kpt-set":"project"}
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: iap-ingress-config
