# TODO(Bobgy): should this be moved to a central place?
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kf-admin
  annotations:
    iam.gke.io/gcp-service-account: dev-5-14-admin@gongyuan-dev.iam.gserviceaccount.com # {"$kpt-set":"gcp-sa-admin"}
