apiVersion: storage.cnrm.cloud.google.com/v1beta1
kind: StorageBucketAccessControl
metadata:
  name: kfp-gcs-client
spec:
  bucketRef:
    name: kubeflow-pipelines-artifacts
  entity: user-KUBEFLOW-NAME-user@PROJECT.iam.gserviceaccouont.com # {"$kpt-set": "user-sa-entity"}
  role: OWNER
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: kfp-gcs-gateway-wi-user
spec:
  member: serviceAccount:PROJECT.svc.id.goog[kubeflow/kubeflow-pipelines-minio-gcs-gateway] # {"$kpt-set":"kfp-gcs-gateway-ksa-member"}
  role: roles/iam.workloadIdentityUser
  resourceRef:
    apiVersion: iam.cnrm.cloud.google.com/v1beta1
    kind: IAMServiceAccount
    name: KUBEFLOW-NAME-user # {"$kpt-set":"user-sa-name"}
