apiVersion: v1
kind: ServiceAccount
metadata:
  name: kf-admin
  annotations:
    iam.gke.io/gcp-service-account: dev-4-27-admin@gongyuan-pipeline-test.iam.gserviceaccount.com # {"$kpt-set":"gcp-sa-admin"}
