apiVersion: v1
data:
  ADMIN: ""
  USERID_HEADER: kubeflow-userid
  USERID_PREFIX: ""
  WORKLOAD_IDENTITY: ""
  admin: gongyuan@kubeflow.org
  gcp-sa: dev-4-7-user@gongyuan-dev.iam.gserviceaccount.com
kind: ConfigMap
metadata:
  labels:
    kustomize.component: profiles
  name: profiles-config-475bgh929b
  namespace: kubeflow
