apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow
resources:
- ./upstream/overlays/kubeflow

commonLabels:
  kustomize.component: profiles

patchesStrategicMerge:
- patches/manager.yaml
- patches/profiles-config.yaml

configMapGenerator:
- name: namespace-labels-data
  files:
  - namespace-labels.yaml
  
images:
- name: public.ecr.aws/j1r0q0g6/notebooks/access-management
  newName: public.ecr.aws/j1r0q0g6/notebooks/access-management
  newTag: v1.3.0-rc.0
- name: public.ecr.aws/j1r0q0g6/notebooks/profile-controller
  newName: gcr.io/jamxl-kfp-dev/profile-controller
  newTag: kf-v1.3-rc0
